{{- if .Values.RBAC.Enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jira
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jira
subjects:
- kind: ServiceAccount
  name: jira
  namespace: {{ .Release.Namespace }}
{{- end }}
