{{- if .Values.Ingress.Enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  rules:
  - host: {{ .Values.Ingress.Host }}
    http:
      paths: 
      {{- if .Values.Ingress.Path }}
      - path: {{ .Values.Ingress.Path }}
      {{- else }}
      - path: /
      {{- end }}
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.Ingress.ServicePort }}
{{- end }}
